/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { WebhookDeliveryArray } from './WebhookDeliveryArray';
import type { WebhookResponseArray } from './WebhookResponseArray';
import type { WebhookTriggerArray } from './WebhookTriggerArray';
export type WebhookProperties = {
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Boolean to indicate if the webhook is active
     */
    active?: boolean;
    /**
     * A title for the webhook for easy recognition.
     */
    title: string;
    /**
     * A 24-character secret for the webhook. It's generated by Firefly III when saving a new webhook. If you submit a new secret through the PUT endpoint it will generate a new secret for the selected webhook, a new secret bearing no relation to whatever you just submitted.
     */
    readonly secret?: string;
    triggers?: WebhookTriggerArray;
    responses?: WebhookResponseArray;
    deliveries?: WebhookDeliveryArray;
    /**
     * The URL of the webhook. Has to start with `https`.
     */
    url: string;
};

