/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type BudgetLimitUpdate = {
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Start date of the budget limit.
     */
    start?: string;
    /**
     * End date of the budget limit.
     */
    end?: string;
    /**
     * The budget ID of the associated budget.
     */
    readonly budget_id?: string;
    /**
     * Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.
     */
    readonly object_has_currency_setting?: boolean;
    /**
     * The currency ID of the currency associated with this object.
     */
    currency_id?: string;
    /**
     * The currency name of the currency associated with this object.
     */
    currency_name?: string;
    /**
     * The currency code of the currency associated with this object.
     */
    currency_code?: string;
    readonly currency_symbol?: string;
    readonly currency_decimal_places?: number;
    /**
     * The currency ID of the administration's primary currency.
     */
    readonly primary_currency_id?: string;
    /**
     * The currency name of the administration's primary currency.
     */
    readonly primary_currency_name?: string;
    /**
     * The currency code of the administration's primary currency.
     */
    readonly primary_currency_code?: string;
    /**
     * The currency symbol of the administration's primary currency.
     */
    readonly primary_currency_symbol?: string;
    /**
     * The currency decimal places of the administration's primary currency.
     */
    readonly primary_currency_decimal_places?: number;
    /**
     * Period of the budget limit. Only used when auto-generated by auto-budget.
     */
    readonly period?: string | null;
    amount?: string;
    /**
     * The amount of this budget limit in the user's primary currency, if the original amount is in a different currency.
     */
    readonly pc_amount?: string | null;
    /**
     * Will be in the primary currency if this is turned on by the user.
     */
    readonly spent?: string | null;
    /**
     * Some notes for this specific budget limit.
     */
    notes?: string | null;
    /**
     * Whether or not to fire the webhooks that are related to this event.
     */
    fire_webhooks?: boolean;
};

